ClueRide/server

pom.xml
src/main/java/com/clueride/domain/account/member/MemberServiceImpl.java
src/main/java/com/clueride/domain/account/member/MemberStore.java
src/main/java/com/clueride/domain/account/member/MemberStoreJpa.java
src/main/resources/META-INF/persistence.xml

- Adds MemberStore and JPA implementation.
- Updates persistence.xml to use container's JNDI Data Source.
- Turns off auto-gen of tables (changed to update for now).
- Brings in Mail API to support one field of the Member class.

Explore Hibernate DataStore

---

pom.xml
src/test/resources/log4j.properties

- Adds SLF4J libraries that Weld complained about.
- Provides log4j.properties -- turns off all logging from Weld.

Logging with Log4J

---

src/main/java/com/clueride/auth/Secured.java
src/main/java/com/clueride/auth/access/AccessTokenService.java
src/main/java/com/clueride/auth/access/AccessTokenServiceImpl.java
src/main/java/com/clueride/auth/filter/AuthenticationFilter.java
src/main/java/com/clueride/domain/account/member/MemberServiceImpl.java
src/main/java/com/clueride/util/Resources.java
src/main/resources/log4j.properties

- Adds AuthenticationFilter which responds to each REST call by virtue
of extending ContainerRequestFilter.
- Adds @Secured qualifier annotation for protected REST resources.
- Adds annotation to the MemberWebService to protect it.
- Adds interface and empty implementation for the AccessTokenService
responsible for validating the AccessToken against the 3rd-party auth
provider.
NOTE: There were some interesting NPEs until I was able to setup a "bean-style"
constructor; not able to use constructor-based injection for the AuthenticationFilter.
Further, none of the injected services are available at the time of construction.
Logging was a notable service.
Logging is also settling out within this commit:
- Log4j.properties as part of src/main/resources.
- Changed JUL over to SLF4J when …

CA-391 Check @Secured for session validation

---

pom.xml
src/main/java/com/clueride/auth/filter/AuthenticationFilter.java
src/main/java/com/clueride/config/ConfigService.java
src/main/java/com/clueride/config/ConfigServiceImpl.java
src/main/resources/log4j.properties
src/main/resources/reference.conf

- Adds TypeSafe Config to pom.xml.
- Adds Service and implementation for Config.
- Adds reference.conf from previous incarcation of this app.
Also provides for file logger for the application.
NOTE: There's not a lot of Java EE 7 specific configuration support;
TypeSafe Config addresses the issues which were discussed.

CA-392 Configuration under WildFly: TypeSafe Config or other choices?

---

pom.xml
src/main/java/com/clueride/RecordNotFoundException.java
src/main/java/com/clueride/auth/AuthenticationConnection.java
src/main/java/com/clueride/auth/AuthenticationConnectionAuth0.java
src/main/java/com/clueride/auth/access/AccessToken.java
src/main/java/com/clueride/auth/access/AccessTokenService.java
src/main/java/com/clueride/auth/access/AccessTokenServiceImpl.java
src/main/java/com/clueride/auth/identity/ClueRideIdentity.java
src/main/java/com/clueride/auth/identity/IdentityStore.java
src/main/java/com/clueride/auth/identity/IdentityStoreAuth0.java

- Adds implementation for AccessToken Service turning opaque token into
ClueRide Identity from 3rd-party authentication service.
- Adds the definition of a ClueRideIdentity.
- Adds connection code for 3rd-party authentication service (Auth0).
This also brings in a number of libraries to support:
- @Immutable
- Optional<>
- Jackson JSON handling
- HttpClient code for conversation with 3rd-party Authentication service.

CA-393 Complete connection to Auth0

---

src/main/java/com/clueride/domain/account/member/MemberStoreJpa.java
src/main/java/com/clueride/domain/account/principal/BadgeOsPrincipal.java
src/main/java/com/clueride/domain/account/principal/BadgeOsPrincipalFilter.java
src/main/java/com/clueride/domain/account/principal/BadgeOsPrincipalService.java
src/main/java/com/clueride/domain/account/principal/BadgeOsPrincipalServiceImpl.java
src/main/java/com/clueride/domain/account/principal/BadgeOsPrincipalStore.java
src/main/java/com/clueride/domain/account/principal/BadgeOsPrincipalStoreJpa.java
src/main/java/com/clueride/domain/account/principal/BadgeOsPrincipalWebService.java
src/main/java/com/clueride/domain/badge/event/BadgeEventStoreJpa.java
src/main/java/com/clueride/util/Resources.java
src/main/resources/META-INF/persistence.xml

- Adds BadgeOsPrincipal suite of web service, service, store, entity and a filter for searching users.
- Updates persistence.xml and Resources to handle two datasources and entities (PersistenceContext).
- Updates Store implementations to distinguish which EntityManagers it will use.
Tested using Postman to retrieve list of BadgeOS user/principals.

CA-396 Retrieve list of User from the BadgeOS system

---

pom.xml
src/main/java/com/clueride/auth/filter/AuthenticationFilter.java
src/main/java/com/clueride/auth/identity/ClueRideIdentity.java
src/main/java/com/clueride/auth/identity/IdentityStoreAuth0.java
src/main/java/com/clueride/auth/state/AccessStateService.java
src/main/java/com/clueride/auth/state/AccessStateServiceImpl.java
src/main/java/com/clueride/auth/state/AccessStateWebService.java
src/main/java/com/clueride/domain/account/member/Member.java
src/main/java/com/clueride/domain/account/member/MemberService.java
src/main/java/com/clueride/domain/account/member/MemberServiceImpl.java
src/main/java/com/clueride/domain/account/member/MemberStore.java
src/main/java/com/clueride/domain/account/member/MemberStoreJpa.java
src/test/java/com/clueride/auth/state/AccessStateServiceImplTest.java
src/test/java/com/clueride/auth/state/TestResources.java
src/test/java/com/clueride/auth/state/testng-verbose-logging.xml

- Adds webservice and service for AccessState along with TestNG unit test.
- Begins work on CA-405 to update records when we get a new Identity.
Also:
- Removes forced parsing of URL and InternetAddress fields at build() time.

CA-404 REST API for Registration Check

---

src/main/resources/log4j.properties

Well, just updated the date format since WildFly is fairly tied to
its built-in logging sub-system.  More details on the ticket.

CA-402 Logback implementation of SLF4J

---

src/main/java/com/clueride/auth/ClueRideSessionDto.java
src/main/java/com/clueride/domain/badge/BadgeStoreJpa.java
src/main/java/com/clueride/domain/course/CourseService.java
src/main/java/com/clueride/domain/course/CourseServiceImpl.java
src/main/java/com/clueride/domain/location/Location.java
src/main/java/com/clueride/domain/location/LocationBuilder.java
src/main/java/com/clueride/domain/location/LocationService.java
src/main/java/com/clueride/domain/location/LocationServiceImpl.java
src/main/java/com/clueride/domain/location/LocationStoreJpa.java
src/main/java/com/clueride/domain/location/LocationWebService.java
src/main/java/com/clueride/domain/outing/OutingView.java
src/main/java/com/clueride/domain/path/Path.java
src/main/java/com/clueride/domain/path/PathForCourse.java
src/main/java/com/clueride/domain/path/PathForCourseBuilder.java
src/main/java/com/clueride/domain/path/PathForCourseStore.java
src/main/java/com/clueride/domain/path/PathForCourseStoreJpa.java
src/main/java/com/clueride/network/path/PathService.java
src/main/java/com/clueride/network/path/PathServiceImpl.java
src/main/java/com/clueride/network/path/PathStore.java
src/main/java/com/clueride/network/path/PathStoreJpa.java

- Adds WebService for populating the Location Cache within the front-end.
- Amends the existing Location object to hold LocationType and LatLon instances; not quite ready for GeoJSON, but it has the data to build this on the front-end for now.
- Adds to the CourseService to retrieve a list of the Locations. This includes making use of the Path service to retrieve a list of Paths.
- Adds method to PathService for retrieving the list of Paths for a Course; also adds the JPA Store to support this.
- There's a field for the Course in the Session DTO, but not yet being used.

Location Web Service and Supporting Cast

---

src/main/java/com/clueride/domain/image/ImageEntity.java
src/main/java/com/clueride/domain/image/ImageServiceImpl.java
src/main/java/com/clueride/domain/puzzle/PuzzleBuilder.java
src/main/java/com/clueride/domain/puzzle/PuzzleService.java
src/main/java/com/clueride/domain/puzzle/PuzzleServiceImpl.java
src/main/java/com/clueride/domain/puzzle/PuzzleStoreJpa.java
src/main/java/com/clueride/domain/puzzle/PuzzleWebService.java

- Accepts request for a blank Puzzle to be filled out (wanted to
initialize this server-side.
- Accepts PuzzleBuilder which has been filled out for persisting.
- Adjusts ImageEntity to allow construction for JPA and REST (including
a constructor that accepts the URL as a string).
- Adjusts PuzzleBuilder to allow construction by the REST API.

SVR-15 API Support for adding a new Puzzle

---

src/main/java/com/clueride/domain/location/LocationService.java
src/main/java/com/clueride/domain/location/LocationServiceImpl.java
src/main/java/com/clueride/domain/location/LocationStore.java
src/main/java/com/clueride/domain/location/LocationStoreJpa.java
src/main/java/com/clueride/domain/location/LocationWebService.java

- Adds methods supporting the removal of a Location.
This leaves the Node intact; may want to change that later.
Example of a Delete which may suffer from a detached instance:
https://stackoverflow.com/questions/17027398/java-lang-illegalargumentexception-removing-a-detached-instance-com-test-user5

SVR-17 API for deleting unwanted Location

---

pom.xml
src/main/java/com/clueride/aop/badge/BadgeCaptureInterceptor.java
src/main/java/com/clueride/auth/filter/AuthenticationFilter.java
src/main/java/com/clueride/auth/session/ClueRideSession.java
src/main/java/com/clueride/auth/session/ClueRideSessionDto.java
src/main/java/com/clueride/auth/session/ClueRideSessionProducer.java
src/main/java/com/clueride/auth/session/ClueRideSessionService.java
src/main/java/com/clueride/auth/session/ClueRideSessionServiceImpl.java
src/main/java/com/clueride/domain/account/member/MemberServiceImpl.java
src/main/java/com/clueride/domain/account/principal/BadgeOsPrincipalServiceImpl.java
src/main/java/com/clueride/domain/badge/BadgeServiceImpl.java
src/main/java/com/clueride/domain/course/Course.java
src/main/java/com/clueride/domain/course/CourseServiceImpl.java
src/main/java/com/clueride/domain/course/GameCourse.java
src/main/java/com/clueride/domain/game/GameState.java
src/main/java/com/clueride/domain/game/GameStateServiceImpl.java
src/main/java/com/clueride/domain/game/ssevent/SSEventService.java
src/main/java/com/clueride/domain/game/ssevent/SSEventServiceImpl.java
src/main/java/com/clueride/domain/invite/InviteServiceImpl.java
src/main/java/com/clueride/domain/location/Location.java
src/main/java/com/clueride/domain/location/LocationServiceImpl.java
src/main/java/com/clueride/domain/outing/OutingServiceImpl.java
src/main/java/com/clueride/domain/path/Path.java
src/main/java/com/clueride/domain/puzzle/PuzzleService.java
src/main/java/com/clueride/domain/puzzle/PuzzleServiceImpl.java
src/main/java/com/clueride/domain/puzzle/PuzzleWebService.java
src/main/java/com/clueride/domain/puzzle/answer/AnswerPost.java
src/main/java/com/clueride/domain/puzzle/answer/AnswerSummary.java
src/main/java/com/clueride/domain/puzzle/state/PuzzleState.java
src/main/java/com/clueride/domain/puzzle/state/PuzzleStateService.java

- Adds AnswerPost object containing puzzle reference and answer.
- Adds AnswerSummary which pulls together a summary of answers for a puzzle on an outing.
- Adds API for posting the answer and returning the summary along with
updates to the session objects.
Not yet broadcasting the Summary -- awaiting work to turn this into a
trunk that pushes all events.
Refactors:
- Pieces of the Session
- Step is no longer needed (just use location and puzzle)
Significant:
- Working around a weak spot in creating Session objects -- now placing these in
a map keyed by the access token. (need to be careful using test tokens)
- Moves us to Java 8 to take advantage of `Map.merge()`.

SVR-21 Support for posting an Answer

---

src/main/java/com/clueride/domain/badge/event/BadgeEventService.java
src/main/java/com/clueride/domain/badge/event/BadgeEventServiceImpl.java
src/main/java/com/clueride/domain/game/GameStateServiceImpl.java

- Adds signature to BadgeEvent service to allow sending the same
BadgeEvent to all team members.
- Updates GameStateService to build events for Assembly, Arrival, and Course Completion.
This will be over-inclusive until SVR-32 and PLAY-64 (Take attendance) are complete.

SVR-31 BadgeEvent Generation for Game Completion

---

src/main/java/com/clueride/domain/image/ImageByLocation.java
src/main/java/com/clueride/domain/image/ImageLink.java
src/main/java/com/clueride/domain/image/ImageLinkEntity.java
src/main/java/com/clueride/domain/image/ImageService.java
src/main/java/com/clueride/domain/image/ImageServiceImpl.java
src/main/java/com/clueride/domain/image/ImageStore.java
src/main/java/com/clueride/domain/image/ImageStoreImpl.java
src/main/java/com/clueride/domain/image/ImageUploadRequest.java
src/main/java/com/clueride/domain/image/ImageWebService.java
src/main/java/com/clueride/domain/location/Location.java
src/main/java/com/clueride/domain/location/LocationBuilder.java

- Renames ImageEntity to ImageLinkEntity.
- Places new (immutable) ImageLink class inside the immutable Location.
- Removes the Image URLs property on the Location.
Defers to the Front End to match up featured Image ID on location against
the full list of imageLinks.

SVR-34 Refactor ImageEntity to make it easier on the front-end

---

src/main/java/com/clueride/domain/account/member/Member.java
src/main/java/com/clueride/domain/account/member/MemberBuilder.java
src/main/java/com/clueride/domain/account/member/MemberServiceImpl.java
src/main/java/com/clueride/domain/account/member/MemberWebService.java

- Adds new column to the Member table, builder, and DTO.
This is coming from the ClueRideIdentity, but may not be fully connected;
CA-405 has more details and a TODO dropped in MemberServiceImpl.

SVR-37 Member Service not returning the Image URL

---

src/main/java/com/clueride/auth/AuthenticationConnectionAuth0.java

- Adds logging message when access token rejected.

SVR-43 Access Token not accepted but cause isn't being logged

---

src/main/java/com/clueride/domain/team/TeamStoreJpa.java
src/main/java/com/clueride/domain/team/TeamWebService.java

- Adds web service endpoint (service layer through DAO were in place).
- Modifies the Store's query to join the `outing_view` to pickup recent
outings in descending date order to put most recent at top.
This unfortunately will place a newly created team at the bottom, so we
may want to add a creation date column in the future.

SVR-47 API for List of current Teams

---

src/main/java/com/clueride/auth/access/AccessTokenService.java
src/main/java/com/clueride/auth/access/AccessTokenServiceImpl.java

- Sets the expiration time on the cache to 24 hours.
Also removes an unused `emptyCache()` method.

SVR-48 Need to expire Access Tokens

---

src/main/java/com/clueride/domain/location/Location.java
src/main/java/com/clueride/domain/location/LocationBuilder.java
src/main/java/com/clueride/domain/location/LocationServiceImpl.java

- Changes the Builder's return type from LocLink to Optional<LocLink>.
- Replaces tests for null with tests for `isPresent()`.
- Hibernate likes an actual object where it can place the null -- an @Nullable field.
- The real issue comes when working with this value -- which may or may not be present -- and allowing that test to occur instead of a null value check.

SVR-54 Make the Main Loc Link explicitly Optional

---

pom.xml
src/main/java/com/clueride/badgeos/BadgeOSCredentials.java
src/main/java/com/clueride/badgeos/BadgeOSSessionService.java
src/main/java/com/clueride/badgeos/BadgeOSSessionServiceImpl.java
src/main/java/com/clueride/badgeos/BadgeOSWebService.java
src/main/java/com/clueride/badgeos/Nonce.java
src/main/java/com/clueride/badgeos/NonceType.java
src/main/java/com/clueride/config/ConfigService.java
src/main/java/com/clueride/config/ConfigServiceImpl.java
src/main/resources/log4j.properties
src/main/resources/reference.conf

- Adds new BadgeOS Service with webservice that supports retrieving
Nonces from a WordPress session that we've logged into using credentials
stored in the app server.
This also amended the log4j.properties to allow debugging of the connection code.
Adds more complete set of dependencies for HttpComponents.

SVR-60 Establish BadgeOS Session

---

src/main/java/com/clueride/domain/location/LocationEntity.java
src/main/java/com/clueride/domain/location/LocationService.java
src/main/java/com/clueride/domain/location/LocationServiceImpl.java
src/main/java/com/clueride/domain/location/LocationWebService.java
src/main/java/com/clueride/domain/location/loclink/LocLinkService.java
src/main/java/com/clueride/domain/location/loclink/LocLinkServiceImpl.java
src/main/java/com/clueride/domain/location/loclink/LocLinkWebService.java

- Uses Loc Link *Entity* which has been persisted instead of Entity created from
another instance.
- Switches the Loc Type ID to use the one from the instance instead of
the flattened value.
- Now throwing any Malformed URLs back to the client (see CI-56).

SVR-81 Trouble saving updated Attractions - Main Link

---

src/main/java/com/clueride/DefaultExceptionMapper.java

- Adds default handler for all `Throwable` (with the exception of an
internal DefaultOptionsMethodException -- see SVR-84).

SVR-83 Add Exception Mapper handling

---

src/main/java/com/clueride/DefaultExceptionMapper.java
src/main/java/com/clueride/domain/location/Location.java
src/main/java/com/clueride/domain/location/LocationEntity.java
src/main/java/com/clueride/domain/location/LocationServiceImpl.java
src/main/java/com/clueride/domain/place/ScoredLocationServiceImpl.java

- Removes LocationTypeEntity from LocationEntity and replaces it with LocationTypeId
which is the value we keep in the database table.
Also adds logging of stack trace when we encounter an uncaught exception
that we return to the REST clients.

SVR-36 Tidy up Location Type for the Location

---

pom.xml

- Adds repos to the pom.xml so it can find the hard-to-satisfy dependencies brought in by the geotools.

SVR-95 Get build going on pavo

---

pom.xml
src/main/java/com/clueride/domain/attraction/Attraction.java
src/main/java/com/clueride/domain/attraction/AttractionEntity.java
src/main/java/com/clueride/domain/attraction/AttractionNotFoundException.java
src/main/java/com/clueride/domain/attraction/AttractionService.java
src/main/java/com/clueride/domain/attraction/AttractionServiceImpl.java
src/main/java/com/clueride/domain/attraction/AttractionStore.java
src/main/java/com/clueride/domain/attraction/AttractionStoreJpa.java
src/main/java/com/clueride/domain/attraction/AttractionWebService.java
src/main/java/com/clueride/domain/flag/FlagEntity.java
src/main/java/com/clueride/domain/flag/FlagService.java
src/main/java/com/clueride/domain/flag/FlagServiceImpl.java
src/main/java/com/clueride/domain/flag/FlagStore.java
src/main/java/com/clueride/domain/flag/FlagStoreJpa.java
src/main/java/com/clueride/domain/flag/FlagWebService.java
src/main/java/com/clueride/domain/outing/OutingStore.java
src/main/java/com/clueride/domain/outing/OutingStoreJpa.java
src/test/java/com/clueride/domain/flag/TestResources.java

- Provides REST API to save new flag instances to the DB.
- Provides REST API to retrieve list of all Flag instances (open or otherwise).
- Starts moving Location over to Attraction.
Also some pom.xml cleanup.

SVR-96 Back-end Support (and API) for Managing Incomplete Attractions

---

src/main/java/com/clueride/auth/InvalidAuthTokenException.java
src/main/java/com/clueride/auth/access/AccessTokenService.java
src/main/java/com/clueride/auth/access/AccessTokenServiceImpl.java
src/main/java/com/clueride/auth/session/ClueRideSessionDto.java
src/main/java/com/clueride/auth/session/ClueRideSessionProducer.java
src/main/java/com/clueride/auth/session/ClueRideSessionService.java
src/main/java/com/clueride/auth/session/ClueRideSessionServiceImpl.java
src/main/java/com/clueride/auth/state/AccessStateService.java
src/main/java/com/clueride/auth/state/AccessStateServiceImpl.java
src/main/java/com/clueride/auth/state/AccessStateWebService.java
src/main/java/com/clueride/auth/state/AccountState.java
src/main/java/com/clueride/domain/account/member/Member.java
src/main/java/com/clueride/domain/account/member/MemberEntity.java
src/main/java/com/clueride/domain/account/member/MemberService.java
src/main/java/com/clueride/domain/account/member/MemberServiceImpl.java
src/main/java/com/clueride/domain/account/member/MemberWebService.java
src/main/java/com/clueride/domain/course/CourseServiceImpl.java
src/main/java/com/clueride/domain/game/GameStateServiceImpl.java
src/main/java/com/clueride/domain/invite/InviteService.java
src/main/java/com/clueride/domain/outing/NoSessionOutingException.java
src/main/java/com/clueride/domain/outing/OutingServiceImpl.java

- Adds endpoint for setting up a new accounts under AccessStateService.
- Endpoint service also prepares the Session DTO.
- Moves validation of the Access Token under that service.
- Refactors Session Producer functionality under the service rather than the provider.
- Adds alias for Member/Profile property to set the Email (EmailAddress is main attribute).
- Image URL was not quite handled for MemberEntity.
- MemberService now returns Entity to allow mutation with BadgeOS ID.
Toward endpoint robustness (for future):
- Adds convenience method to Session DTO to tell if there is an outing assigned to the session.
- New Runtime Exceptions for improved reporting.
- The `cross-check` endpoint had been intended to handle creation and updates to accounts, but this should be used only for updates …

SVR-108 Make sure Member Account is generated if missing

---

src/main/java/com/clueride/auth/state/AccessStateServiceImpl.java
src/main/java/com/clueride/domain/course/CourseService.java
src/main/java/com/clueride/domain/course/CourseServiceImpl.java
src/main/java/com/clueride/domain/course/CourseWebService.java
src/main/java/com/clueride/domain/outing/Outing.java
src/main/java/com/clueride/domain/outing/OutingConstants.java
src/main/java/com/clueride/domain/outing/OutingEntity.java
src/main/java/com/clueride/domain/outing/OutingService.java
src/main/java/com/clueride/domain/outing/OutingServiceImpl.java
src/main/java/com/clueride/domain/outing/OutingStore.java
src/main/java/com/clueride/domain/outing/OutingStoreJpa.java

- Adds new API endpoint to set the default course for the Eternal Outing.
- Adds new method to the OutingService
- Adds new OutingEntity to work with just the table and not the full view (we need to persist records here).
- Adds new method to the OutingStore to perform the update.
Also raises the Eternal Outing to Constant status.

SVR-126 Support selecting the next course to use as a "default"

---

src/main/java/com/clueride/auth/session/ClueRideSessionDto.java
src/main/java/com/clueride/auth/session/ClueRideSessionServiceImpl.java
src/main/java/com/clueride/auth/state/AccessStateServiceImpl.java
src/main/java/com/clueride/domain/course/CourseService.java
src/main/java/com/clueride/domain/course/CourseServiceImpl.java
src/main/java/com/clueride/domain/course/CourseWebService.java
src/main/java/com/clueride/domain/game/GameStateService.java
src/main/java/com/clueride/domain/game/GameStateServiceImpl.java
src/main/java/com/clueride/domain/game/GameStateWebService.java
src/main/java/com/clueride/domain/game/ssevent/SSEventServiceImpl.java
src/main/java/com/clueride/domain/location/LocationServiceImpl.java
src/main/java/com/clueride/domain/outing/OutingConstants.java
src/main/java/com/clueride/domain/outing/OutingServiceImpl.java
src/test/java/com/clueride/domain/game/GameStateServiceImplTest.java

- Adds Reset endpoint for the GameState which calls the service layer to place
an empty GameState within the Session's GameState Map, keyed by the Outing ID.
- Pulls OutingView from the Session and records just the OutingID permitting the
Outing details to be updated in the DB without having to update any live sessions.

SVR-127 Support resetting the Game State
