- src/main/java/com/clueride/domain/account/member/Member.java
- Provides annotation for Generated ID.
- Removes link to the Badges (use separate API for that).
> CA-394 Tidy up the full Member annotation and MemberStore implementation

- src/main/java/com/clueride/util/filter/CorsFilter.java
- src/main/java/com/clueride/util/filter/JSONPRequestFilter.java
- src/main/resources/reference.conf
- src/main/webapp/WEB-INF/web.xml
- Adds the CORS filter which appends appropriate headers to each request.
- Refactors filters under util.filter package.
- Adds web.xml to provide ordering for the filters.
Also adds a configuration entry for the Origins which are allowed
(wide open in this case).
> CA-399 Add CORS Filter

- src/main/java/com/clueride/MalformedUrlWithinDBException.java
- src/main/java/com/clueride/auth/filter/AuthenticationFilter.java
- src/main/java/com/clueride/domain/account/principal/BadgeOsPrincipalStoreJpa.java
- src/main/java/com/clueride/domain/account/principal/PrincipalServiceImpl.java
- src/main/java/com/clueride/domain/badge/Badge.java
- src/main/java/com/clueride/domain/badge/BadgeService.java
- src/main/java/com/clueride/domain/badge/BadgeServiceImpl.java
- src/main/java/com/clueride/domain/badge/BadgeStore.java
- src/main/java/com/clueride/domain/badge/BadgeStoreJpa.java
- src/main/java/com/clueride/domain/badge/BadgeType.java
- src/main/java/com/clueride/domain/badge/BadgeTypeService.java
- src/main/java/com/clueride/domain/badge/BadgeTypeServiceMappedImpl.java
- src/main/java/com/clueride/domain/badge/BadgeWebService.java
- Adds full stack for a Badge: Web Service, Service, Store, and Entity
- Trims down the PrincipalService to act as a proxy for BadgeOSPrincipal Service (prepares for cleanup of this service).
> CA-400 Badges REST API

- pom.xml
- src/main/java/com/clueride/domain/invite/InviteServiceImpl.java
- src/main/java/com/clueride/domain/invite/InviteStore.java
- src/main/java/com/clueride/domain/invite/InviteStoreJpa.java
- src/main/java/com/clueride/domain/invite/InviteWebService.java
- Adds WebService endpoints for accept/decline InviteId
- Adds supporting code to ServiceImpl
- Adds first 'merge' operation under Hibernate/WildFly -- required a UserTransaction.
> CA-413 Endpoints for accepting/declining an invite

- src/main/java/com/clueride/auth/ClueRideSession.java
- src/main/java/com/clueride/auth/ClueRideSessionDto.java
- src/main/java/com/clueride/auth/ClueRideSessionProducer.java
- src/main/java/com/clueride/domain/account/principal/BadgeOsPrincipalServiceImpl.java
- src/main/java/com/clueride/domain/invite/InviteService.java
- src/main/java/com/clueride/domain/invite/InviteServiceImpl.java
- src/main/java/com/clueride/domain/invite/InviteWebService.java
- src/main/java/com/clueride/domain/outing/OutingService.java
- src/main/java/com/clueride/domain/outing/OutingServiceImpl.java
- src/main/java/com/clueride/domain/outing/OutingWebService.java
- Updates ClueRideSessionProducer to add both Invite and Outing to the DTO.
- Adds endpoint for retrieving the session Invite (next invite).
- Adds endpoint for retrieving the session Outing (active OutingView).
> CA-376 How does an Outing get associated with a session

- src/main/java/com/clueride/util/network/README.md
- Deletes the util.network package.
- Tidies up the pom.xml.
> SVR-1 Clean up the util.network package -- no longer needed.

- src/main/java/com/clueride/network/edge/EdgeService.java
- src/main/java/com/clueride/network/edge/EdgeServiceImpl.java
- src/main/java/com/clueride/network/edge/EdgeStore.java
- src/main/java/com/clueride/network/edge/EdgeStoreJpa.java
- src/main/java/com/clueride/network/edge/EdgeWebService.java
- Adds WebService endpoint, service call, and Store method for retrieving GeoJSON representation of an Edge.
This places the logic of assembling the JSON within the Database. It required Native SQL, but it looks fairly easy to maintain
and carry forward into other GeoJSON requests.
> SVR-2 Service to provide FeatureCollection in GeoJSON to front-end

- src/main/java/com/clueride/network/path/PathGeometry.java
- src/main/java/com/clueride/network/path/PathService.java
- src/main/java/com/clueride/network/path/PathServiceImpl.java
- src/main/java/com/clueride/network/path/PathStore.java
- src/main/java/com/clueride/network/path/PathStoreImpl.java
- src/main/java/com/clueride/network/path/PathWebService.java
- Web Service, Service, and JPA store against PathGeometry object which fronts a PostGIS SQL statement that assembles the GeoJson.
> SVR-3 Provide Service that retrieves Paths and their Geometry

- src/main/java/com/clueride/auth/ClueRideSessionDto.java
- src/main/java/com/clueride/auth/ClueRideSessionProducer.java
- src/main/java/com/clueride/domain/game/GameState.java
- src/main/java/com/clueride/domain/game/GameStateService.java
- src/main/java/com/clueride/domain/game/GameStateServiceImpl.java
- src/main/java/com/clueride/domain/game/GameStateWebService.java
- src/main/java/com/clueride/domain/game/ssevent/SSEventServiceImpl.java
- src/main/resources/reference.conf
- Adds Game State WebService and Service supporting Team Assembled, Arrival, and Departure.
- Now Placing Game State for the session in the ClueRideSessionDto.
- Expands scope of the event to include the fully-updated GameState instance. Also improves the generation of the JSON by adding inner class.
- Adds improved configuration for the SSE Host.
> SVR-4 Bring in Game State code from old project

- src/main/java/com/clueride/domain/course/CourseServiceImpl.java
- src/main/java/com/clueride/domain/course/CourseWebService.java
- Supports a simple Course; not completely connected.
> course-web-service

- src/main/java/com/clueride/domain/puzzle/Puzzle.java
- src/main/java/com/clueride/domain/puzzle/PuzzleBuilder.java
- src/main/java/com/clueride/domain/puzzle/PuzzleStoreJpa.java
- src/main/java/com/clueride/domain/puzzle/PuzzleWebService.java
- The web service itself was the only class that wasn't created already.
- Small adjustments for the JPA under WildFly.
> Puzzle Web Service and supporting services

- src/main/java/com/clueride/domain/team/TeamWebService.java
- Adds TeamWebService to front an existing TeamService to retrieve a Team by ID.
> team-web-service

- src/main/java/com/clueride/domain/image/ImageEntity.java
- src/main/java/com/clueride/domain/location/Location.java
- src/main/java/com/clueride/domain/location/LocationBuilder.java
- Adds ImageEntity to represent records in the `image` table.
- Amends the LocationBuilder to reference the ImageEntity to obtain the URL to present.
Some cleanup in the direction we're headed.
> SVR-6 API Support for Featured Images

- src/main/java/com/clueride/domain/location/LocationBuilder.java
- src/main/java/com/clueride/domain/location/LocationService.java
- src/main/java/com/clueride/domain/location/LocationServiceImpl.java
- src/main/java/com/clueride/domain/location/LocationStoreJpa.java
- src/main/java/com/clueride/domain/location/LocationWebService.java
- src/main/java/com/clueride/domain/place/Establishment.java
- src/main/java/com/clueride/domain/place/HoursOfOperation.java
- src/main/java/com/clueride/domain/place/README.md
- src/main/java/com/clueride/domain/place/ScoredLocation.java
- src/main/java/com/clueride/domain/place/ScoredLocationService.java
- src/main/java/com/clueride/domain/place/ScoredLocationServiceImpl.java
- Implements full stack for Nearest Locations (all of them at this time).
- Brings in supporting classes: Establishment, HoursOfOperation, ScoredLocation.
Readiness Level is running, but perhaps not correctly.
> SVR-11 Ready for Nearest Marker REST API

- src/main/java/com/clueride/domain/location/LocationBuilder.java
- src/main/java/com/clueride/domain/location/LocationService.java
- src/main/java/com/clueride/domain/location/LocationServiceImpl.java
- src/main/java/com/clueride/domain/location/LocationStore.java
- src/main/java/com/clueride/domain/location/LocationStoreJpa.java
- src/main/java/com/clueride/domain/location/LocationWebService.java
- src/main/java/com/clueride/domain/location/latlon/LatLonStoreJpa.java
- Adds endpoints for propose and update Locations.
- Adds service and store support for those endpoints.
Also addresses CA-309 (refactoring to remove non-Builder portion of API).
> SVR-12 Ready for Location Endpoint that accepts posting a new Location

- pom.xml
- src/main/java/com/clueride/config/ConfigService.java
- src/main/java/com/clueride/config/ConfigServiceImpl.java
- src/main/java/com/clueride/domain/badge/event/BadgeEventBuilder.java
- src/main/java/com/clueride/domain/image/ImageByLocation.java
- src/main/java/com/clueride/domain/image/ImageEntity.java
- src/main/java/com/clueride/domain/image/ImageService.java
- src/main/java/com/clueride/domain/image/ImageServiceImpl.java
- src/main/java/com/clueride/domain/image/ImageStore.java
- src/main/java/com/clueride/domain/image/ImageStoreImpl.java
- src/main/java/com/clueride/domain/image/ImageUploadRequest.java
- src/main/java/com/clueride/domain/image/ImageWebService.java
- src/main/java/com/clueride/domain/location/LocationBuilder.java
- src/main/resources/reference.conf
- Adds DOs for Images: ImageUploadRequest for MultipartFormDate,
ImageEntity for the URL and
ImageByLocation for the link over to Location.
- Adds Service Layer that coordinates the assembly.
- Adds both file-based and JPA based persistence layer for the image file and metaData
respectively.
- BadgeEvents are flowing via annotation on the endpoint to upload; cleaned up the
handling of empty return values.
> SVR-13 API for accepting image uploads

- src/main/java/com/clueride/domain/image/ImageServiceImpl.java
- src/main/java/com/clueride/domain/location/Location.java
- src/main/java/com/clueride/domain/location/LocationBuilder.java
- src/main/java/com/clueride/domain/location/LocationStoreJpa.java
- Arranges the FeatureImage so it is able to play nice when persisting
the Location updates.
Also moves toward SVR-16: Multiple Images per Location.
> LE-93 Round trip for Image IDs

- src/main/java/com/clueride/domain/location/LocationService.java
- src/main/java/com/clueride/domain/location/LocationServiceImpl.java
- src/main/java/com/clueride/domain/location/LocationWebService.java
- Adds Web endpoint and Service layer.
NOTE: The handling of Location Type is a mess. Opening a ticket
for this: SVR-19.
> SVR-18 API for releasing Featured Images

- src/main/java/com/clueride/domain/puzzle/PuzzleServiceImpl.java
- src/main/java/com/clueride/domain/puzzle/PuzzleStore.java
- src/main/java/com/clueride/domain/puzzle/PuzzleStoreJpa.java
- src/main/java/com/clueride/domain/puzzle/PuzzleWebService.java
- Splits out new Store method for update distinct from new.
This may have been broken earlier and just now noticed.
> SVR-20 API adjustments for Puzzles

- src/main/java/com/clueride/domain/game/GameStateService.java
- src/main/java/com/clueride/domain/game/GameStateServiceImpl.java
- src/main/java/com/clueride/domain/invite/InviteServiceImpl.java
- src/main/java/com/clueride/domain/puzzle/PuzzleService.java
- src/main/java/com/clueride/domain/puzzle/PuzzleServiceImpl.java
- src/main/java/com/clueride/domain/puzzle/PuzzleWebService.java
- src/main/java/com/clueride/domain/puzzle/state/PuzzleState.java
- src/main/java/com/clueride/domain/puzzle/state/PuzzleStateService.java
- src/main/java/com/clueride/domain/puzzle/state/PuzzleStateServiceImpl.java
- Adds PuzzleStateService and Implementation backed by hash maps.
- Changes Post Answer to be served out of the Game State Service to avoid
circular dependency.
> SVR-24 Maintain Puzzle State within the Game State

- src/main/java/com/clueride/domain/game/ssevent/AnswerSummaryEvent.java
- src/main/java/com/clueride/domain/game/ssevent/SSEventServiceImpl.java
- src/main/java/com/clueride/domain/game/ssevent/SSEventType.java
- src/main/resources/reference.conf
- Adds methods supporting Answer Message.
- Moves toward a more general approach for sending the messages.
- Adds configuration values; needs some cleanup.
> SVR-25 Broadcast Answer State

- src/main/java/com/clueride/domain/game/GameState.java
- src/main/java/com/clueride/domain/game/GameStateServiceImpl.java
- Removes the bumpLocation() method on the GameState.Builder
and replaces it with logic within the service.
- Provides caching of the Builder instead of the GameState instance.
> Put actual location in Game State.

- src/main/java/com/clueride/domain/badge/event/BadgeEventServiceImpl.java
- src/main/java/com/clueride/domain/badge/event/BadgeEventStoreJpa.java
- Amends the BadgeEventService and Store to allow persisting the records.
> SVR-27 Badge Capture needs to put records in the database

- src/main/java/com/clueride/domain/game/GameState.java
- src/main/java/com/clueride/domain/game/GameStateService.java
- src/main/java/com/clueride/domain/game/GameStateServiceImpl.java
- Adds logic to check for arrival at last Attraction, and sets
`outingComplete` flag on the GameState when this occurs.
Also cleans up unused signatures.
> SVR-29 New Game State for Completion

- src/main/java/com/clueride/domain/badge/event/BadgeEvent.java
- src/main/java/com/clueride/domain/badge/event/BadgeEventBuilder.java
- src/test/java/com/clueride/domain/badge/event/BadgeEventBuilderTest.java
- Adds column in both Builder and DTO
Test I couldn't get to work; Test Ignored message is back.
> SVR-30 Add JSON column to BadgeEvent for ease of deserialization

- src/main/java/com/clueride/domain/image/ImageService.java
- src/main/java/com/clueride/domain/image/ImageServiceImpl.java
- src/main/java/com/clueride/domain/image/ImageStore.java
- src/main/java/com/clueride/domain/image/ImageStoreImpl.java
- src/main/java/com/clueride/domain/image/ImageWebService.java
- Adds endpoint, service, and DAO method to retrieve the image URLs (by ID)
for a given location.
Verified via Postman.
> SVR-14 Server API support for the List of Image URLs

- src/main/java/com/clueride/domain/image/ImageStore.java
- src/main/java/com/clueride/domain/image/ImageStoreImpl.java
- src/main/java/com/clueride/domain/location/Location.java
- src/main/java/com/clueride/domain/location/LocationService.java
- src/main/java/com/clueride/domain/location/LocationServiceImpl.java
- src/main/java/com/clueride/domain/location/LocationWebService.java
- src/main/java/com/clueride/domain/location/loctype/LocationType.java
- Adds webservice and service methods for setting a new featured image.
- Adds new method to ImageStore for retrieving the image (to be linked).
Also, cleanup of a few related classes and dropped some TODO's for
addressing SVR-36 and LE-76 (LocType and Layers respectively).
> SVR-35 Need endpoint for setting featured image

- src/main/java/com/clueride/domain/team/TeamStoreJpa.java
- src/main/java/com/clueride/domain/team/TeamWebService.java
- Adds API endpoint to web service.
- Updates Store to use UserTransaction.
> SVR-46 WebService Endpoint for creating a new team

- src/main/java/com/clueride/domain/account/member/MemberService.java
- src/main/java/com/clueride/domain/account/member/MemberServiceImpl.java
- src/main/java/com/clueride/domain/account/member/MemberStore.java
- src/main/java/com/clueride/domain/account/member/MemberStoreJpa.java
- src/main/java/com/clueride/domain/account/member/MemberWebService.java
- Adds service call and API endpoint to retrieve list of Member
records that match a given pattern.
> INV-9: Support for Add Member to a Team

- src/main/java/com/clueride/domain/location/category/Category.java
- src/main/java/com/clueride/domain/location/category/CategoryEntity.java
- src/main/java/com/clueride/domain/location/category/CategoryStoreJpa.java
- src/main/java/com/clueride/domain/location/loctype/LocationType.java
- src/main/java/com/clueride/domain/location/loctype/LocationTypeBuilder.java
- Links Category to Location Type record.
- Adds icon information to the Category.
> LE-106 Present Location Category with Location Type

- src/main/java/com/clueride/domain/account/member/MemberService.java
- src/main/java/com/clueride/domain/account/member/MemberServiceImpl.java
- src/main/java/com/clueride/domain/account/member/MemberWebService.java
- src/main/java/com/clueride/domain/account/register/RegisterService.java
- src/main/java/com/clueride/domain/account/register/RegisterServiceImpl.java
- Adds REST API for cross-check.
- Adds simple verification.
- Adds Registration BadgeEvent.
Left comment for update/create of BadgeOS record.
> SVR-69 Provide API for Account Cross Check

- src/main/java/com/clueride/aop/badge/MethodName.java
- src/main/java/com/clueride/domain/achievement/award/AwardAchievementService.java
- src/main/java/com/clueride/domain/achievement/award/AwardAchievementServiceImpl.java
- src/main/java/com/clueride/domain/badge/event/BadgeEventServiceImpl.java
- src/main/java/com/clueride/domain/location/LocationBuilder.java
- Adds new REGISTER MethodName.
- Adds new service method for awarding registration.
- Refactors award functionality to appropriate service.
> SVR-62 Implement awarding of Register App achievement

- src/main/java/com/clueride/aop/badge/BadgeCaptureInterceptor.java
- src/main/java/com/clueride/aop/badge/MethodName.java
- src/main/java/com/clueride/domain/achievement/award/AwardAchievementService.java
- src/main/java/com/clueride/domain/achievement/award/AwardAchievementServiceImpl.java
- src/main/java/com/clueride/domain/achievement/map/ArrivalStepsMapService.java
- src/main/java/com/clueride/domain/achievement/map/ArrivalStepsMapServiceImpl.java
- src/main/java/com/clueride/domain/achievement/map/PageStep.java
- src/main/java/com/clueride/domain/achievement/map/PageStepEntity.java
- src/main/java/com/clueride/domain/achievement/map/PageStepsMapService.java
- src/main/java/com/clueride/domain/achievement/map/PageStepsMapServiceImpl.java
- src/main/java/com/clueride/domain/achievement/map/PageStepsStore.java
- src/main/java/com/clueride/domain/achievement/map/PageStepsStoreJpa.java
- src/main/java/com/clueride/domain/badge/event/BadgeEvent.java
- src/main/java/com/clueride/domain/badge/event/BadgeEventBuilder.java
- src/main/java/com/clueride/domain/page/Page.java
- src/main/java/com/clueride/domain/page/PageEntity.java
- src/main/java/com/clueride/domain/page/PageService.java
- src/main/java/com/clueride/domain/page/PageServiceImpl.java
- src/main/java/com/clueride/domain/page/PageStore.java
- src/main/java/com/clueride/domain/page/PageStoreJpa.java
- src/main/java/com/clueride/domain/page/PageWebService.java
- Adds methods to AwardAchievementService for page visits.
- Adds new service for pages so they can be retrieved by slug.
- Adds new map service for page-to-step map.
- Adds new MethodName entry for `visitPage`.
> SVR-63 Implement awarding of achievement for Visit page X

- src/main/java/com/clueride/domain/achievement/award/AwardAchievementServiceImpl.java
- Adds invocation of awardAchievement for the Completed Course case.
> SVR-65 Implement Complete Course Award (3409)

- src/main/java/com/clueride/domain/badge/BadgeServiceImpl.java
- src/main/java/com/clueride/domain/badge/type/BadgeType.java
- src/main/java/com/clueride/domain/badge/type/BadgeTypeService.java
- src/main/java/com/clueride/domain/badge/type/BadgeTypeServiceMappedImpl.java
- Refactors BadgeType into sub-package.
> SVR-73 Improve BadgeType enumeration and determination

- src/main/java/com/clueride/domain/badge/Badge.java
- src/main/java/com/clueride/domain/badge/BadgeEntity.java
- src/main/java/com/clueride/domain/badge/BadgeService.java
- src/main/java/com/clueride/domain/badge/BadgeServiceImpl.java
- src/main/java/com/clueride/domain/badge/BadgeStore.java
- src/main/java/com/clueride/domain/badge/BadgeStoreJpa.java
- src/main/java/com/clueride/domain/badge/BadgeWebService.java
- Includes BadgeEntity against new `completed_badge` view.
> Put Badge instance back in

- src/main/resources/reference.conf
- Renames tenant to clueride-shared.
> SVR-78 Update tenant and possibly other config in the server.

- src/main/java/com/clueride/domain/location/LocationServiceImpl.java
- Fixes lack of LocType(Entity) for providing the Location Type.
This is a result of not having yet worked out everything about SVR-36.
> SVR-82 Stack trace when updating Attraction - Featured Image

- src/main/java/com/clueride/auth/session/ClueRideSessionDto.java
- src/main/java/com/clueride/domain/game/GameStateServiceImpl.java
- Relies on services to find current course instead of relying on
the presence of the values within the Session DTO.
> SVR-85: Fix NPE on Arrival event

- src/main/java/com/clueride/auth/session/ClueRideSessionProducer.java
- Changes message to log email address.
> SVR-86 Remove logging for Session DTO

- src/main/java/com/clueride/domain/location/LocationService.java
- src/main/java/com/clueride/domain/location/LocationServiceImpl.java
- src/main/java/com/clueride/domain/location/LocationWebService.java
- Adds endpoint for retrieving list of Attractions by Course ID.
> SVR-88 API for returning the Attractions for a given Course

- src/main/java/com/clueride/domain/puzzle/PuzzleEntity.java
- Adds @JsonProperty annotation to rename the property from `answerEntities`
to `answers`.
> SVR-89 Jersey error accepting an update to a Puzzle

- src/main/java/com/clueride/domain/course/CourseService.java
- src/main/java/com/clueride/domain/course/CourseServiceImpl.java
- src/main/java/com/clueride/domain/course/CourseStoreJpa.java
- src/main/java/com/clueride/domain/course/CourseWebService.java
- Added webservice, service, impl, and store calls to support retrieving
all of the Courses.
First use of Java 8 Stream to build each entity from the DB.
> SVR-93 Need API call that retrieves all courses

- src/main/java/com/clueride/domain/badge/progress/BadgeProgress.java
- src/main/java/com/clueride/domain/game/GameStateServiceImpl.java
- src/main/java/com/clueride/domain/puzzle/Puzzle.java
- src/main/java/com/clueride/network/edge/Edge.java
- src/main/resources/log4j.properties
- Fixes some broken imports.
- Adds some logging to chase SSE-23 (which may not be SSE after all)
- Splits Badge Events to a separate log via configuration.
> SVR-95: Smoother Build and Deploy

- pom.xml
- As recommended here: https://stackoverflow.com/a/48739007/3394778
> correct-jenkins-maven-build-issue

- pom.xml
- src/main/java/com/clueride/domain/flag/Flag.java
- src/main/java/com/clueride/domain/flag/FlagEntity.java
- src/main/java/com/clueride/domain/flag/details/FlagDetails.java
- src/main/java/com/clueride/domain/flag/details/FlaggedAttribute.java
- src/main/java/com/clueride/domain/flag/reason/FlagReason.java
- src/test/java/com/clueride/domain/flag/FlagTest.java
- src/test/resources/arquillian.xml
This commit focused on being able to Unit Test under Arquillian.
- Creates Test Case using Arquillian.class:
- @Deployment definition
- Injection of actual instance under test.
- Updates arquillian.xml file to be able to connect to Docker instance running WildFly remotely.
- Updates `pom.xml` to reflect improved understanding of what is needed to test.
Functionally:
- Adds Entity and immutable Flag record (matched with DB table so far).
> SVR-97: Setup Arquillian Testing

- src/main/java/com/clueride/domain/attraction/AttractionService.java
- src/main/java/com/clueride/domain/course/CourseNotFoundException.java
- src/main/java/com/clueride/domain/course/CourseService.java
- src/main/java/com/clueride/domain/course/CourseServiceImpl.java
- src/main/java/com/clueride/domain/course/CourseWebService.java
- src/main/java/com/clueride/domain/flag/FlagService.java
- src/main/java/com/clueride/domain/flag/FlagServiceImpl.java
- src/main/java/com/clueride/domain/flag/FlagStore.java
- src/main/java/com/clueride/domain/flag/FlagStoreJpa.java
- src/main/java/com/clueride/domain/flag/FlagWebService.java
- src/main/java/com/clueride/domain/location/LocationServiceImpl.java
- Introduces endpoint for Flag Service to retrieve flags for a given Course.
- Adds endpoint to Course Service to retrieve Course by ID (the course contains a list of attraction IDs).
- Adds JPA DAO to retrieve any flags matching the attraction IDs.
> SVR-98 Support for retrieving all outstanding flags against a Course

- src/main/java/com/clueride/domain/flag/FlagService.java
- src/main/java/com/clueride/domain/flag/FlagServiceImpl.java
- src/main/java/com/clueride/domain/flag/FlagWebService.java
- src/main/java/com/clueride/domain/flag/reason/FlagReason.java
- Adds endpoint to existing Flag API to return list of Reasons directly from the enum.
> SVR-99 Reasons API for a list of valid Reason codes

- src/main/java/com/clueride/domain/flag/FlagService.java
- src/main/java/com/clueride/domain/flag/FlagServiceImpl.java
- src/main/java/com/clueride/domain/flag/FlagWebService.java
- Adds endpoint supporting retrieval of the list of valid Attributes
of an Attraction that can be flagged.
> SVR-100 Flag Attribute REST API

- src/main/java/com/clueride/domain/location/LocationEntity.java
I don't recall setting the update and insertable flags to false, but it happened in August 2019.
Has this really been broken for that long?
> SVR-103 Changes to Location Type are no longer being persisted

- src/main/java/com/clueride/domain/image/ImageService.java
- src/main/java/com/clueride/domain/image/ImageServiceImpl.java
- src/main/java/com/clueride/domain/image/ImageStore.java
- src/main/java/com/clueride/domain/image/ImageStoreImpl.java
- src/main/java/com/clueride/domain/location/LocationServiceImpl.java
- src/main/java/com/clueride/domain/puzzle/PuzzleEntity.java
- src/main/java/com/clueride/domain/puzzle/PuzzleService.java
- src/main/java/com/clueride/domain/puzzle/PuzzleServiceImpl.java
- src/main/java/com/clueride/domain/puzzle/PuzzleStore.java
- src/main/java/com/clueride/domain/puzzle/PuzzleStoreJpa.java
- src/main/java/com/clueride/domain/puzzle/answer/AnswerEntity.java
- Changes to the ImageService & Store
- Changes to the PuzzleService & Store
Still has a problem trying to remove a Location with Puzzles.
> SVR-104 Constraint violation against image when deleting by ID

- src/main/java/com/clueride/domain/course/CourseEntity.java
- src/main/java/com/clueride/domain/course/CourseService.java
- src/main/java/com/clueride/domain/course/CourseServiceImpl.java
- src/main/java/com/clueride/domain/course/CourseStoreJpa.java
- src/main/java/com/clueride/domain/course/CourseWebService.java
- Adds endpoint for adding new Course.
> SVR-107 Endpoint for persisting a Course (new or otherwise)

- src/main/java/com/clueride/domain/flag/FlagServiceImpl.java
- src/main/java/com/clueride/domain/puzzle/PuzzleEntity.java
- src/main/java/com/clueride/domain/puzzle/PuzzleService.java
- src/main/java/com/clueride/domain/puzzle/PuzzleServiceImpl.java
- src/main/java/com/clueride/domain/puzzle/PuzzleStoreJpa.java
- src/main/java/com/clueride/domain/puzzle/PuzzleWebService.java
- Just needed to get the Cascade properties right.
- Renames the addNew to reflect the fact it can be used for update as well.
- Logging lines for making things easier to follow.
Appears I had run across this before, because I've up-voted this solution: https://stackoverflow.com/questions/26591521/java-lang-illegalstateexception-multiple-representations-of-the-same-entity-wit
> SVR-114 Unable to post Puzzles - Server Side

- src/main/java/com/clueride/domain/attraction/AttractionService.java
- src/main/java/com/clueride/domain/attraction/AttractionServiceImpl.java
- src/main/java/com/clueride/domain/attraction/AttractionStore.java
- src/main/java/com/clueride/domain/attraction/AttractionStoreJpa.java
- src/main/java/com/clueride/domain/attraction/AttractionWebService.java
- src/main/java/com/clueride/domain/attraction/NameFragmentQuery.java
- Adds endpoint for retrieving Attractions that begin with the supplied string.
> SVR-115 Attraction search by name for Auto-Complete/Sugggest

- src/main/java/com/clueride/domain/course/CourseService.java
- src/main/java/com/clueride/domain/course/CourseServiceImpl.java
- src/main/java/com/clueride/domain/course/CourseStoreJpa.java
- src/main/java/com/clueride/domain/course/CourseWebService.java
- Split out the Update (POST) from create new (PUT).
> SVR-107-fix-update

- src/main/java/com/clueride/aop/badge/BadgeCaptureInterceptor.java
- src/main/java/com/clueride/auth/filter/AuthenticationFilter.java
- src/main/java/com/clueride/badgeos/BadgeOSSessionServiceImpl.java
- src/main/java/com/clueride/domain/achievement/map/ArrivalStepStoreJpa.java
- src/main/java/com/clueride/util/filter/CorsFilter.java
- src/test/java/com/clueride/auth/state/AccessStateServiceImplTest.java
- src/test/java/com/clueride/domain/flag/FlagTest.java
- src/test/java/com/clueride/domain/flag/TestResources.java
- src/test/resources/META-INF/persistence.xml
- persistence.xml takes advantage of DataSource within WildFly container.
- Narrows the resources available for the test -- avoiding some CDI issues.
- Increased use of the @TestOnly annotation.
> Cleanup for Arquillian testing

- src/main/java/com/clueride/domain/game/GameState.java
- Changes the 'incrementPathIndex' attribute to cap the indexing once the final destination has been reached.
> SVR-125 Turn off Looping for course completion

- src/main/java/com/clueride/domain/attraction/Attraction.java
- src/main/java/com/clueride/domain/attraction/AttractionEntity.java
- src/main/java/com/clueride/domain/attraction/AttractionServiceImpl.java
- Adds a couple of fields to the Attraction and its Entity.
- Adds method to the AttractionServiceImpl to populate the fields from the LocationTypeService.
> SVR-129 Populate the Location Type fields for an Attraction
